name: Docker Publish

on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dingofs
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GH_TOKEN }}
        path: ./

    - name: List directory contents after download
      run: ls -la

    - name: Extract artifact
      run: tar -xzvf dingofs.tar.gz -C curvefs/docker/debian9

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./curvefs/docker/debian9
        file: ./curvefs/docker/debian9/Dockerfile
        push: true
        tags: |
          dingodatabase/dingofs:latest
